# Generated by Django 2.2.7 on 2019-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('sensorType', models.CharField(max_length=100)),
            ],
        ),
    ]
